DIR = "C:\\Users\\F4900626\\OneDrive - FRG\\Zindi\\Bill Classification in Tunisia Challenge"
TRAIN_DATADIR = "\\Computer Vision - Expensya\\tosend 2\\train"
TRAIN_TEMP_DATADIR = "\\Computer Vision - Expensya\\temp\\train"
TEST_DATADIR = "\\Computer Vision - Expensya\\tosend 2\\test"
TEST_TEMP_DATADIR = "\\Computer Vision - Expensya\\temp\\test"
DATADIR_PICKLE = "pickles\\"
LABELSDIR = "\\Computer Vision - Expensya\\train_labels.csv"
TRAIN_LABELS = "\\Computer Vision - Expensya\\train_labels.csv"